FROM node:20-alpine3.22 AS builder

WORKDIR /app
RUN apk add --no-cache ffmpeg
COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-alpine3.22

WORKDIR /app
RUN apk add --no-cache ffmpeg curl
COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["npm", "start"]
