FROM node:20-alpine3.22

WORKDIR /app

RUN apk add --no-cache ffmpeg curl fontconfig ttf-dejavu

COPY package.json package-lock.json* ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "dev"]
